ALTER TABLE "Client" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkType" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkEntry" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" DISABLE ROW LEVEL SECURITY;
